# filepath: _config.yml
title: Nithun Selva
description: Personal Portfolio and Resume
baseurl: ""
url: "https://nssent25.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal # Changed from minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .git/
  - .github/
  - vendor/